DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS post;

CREATE TABLE usuario (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT UNIQUE NOT NULL,
  upassword TEXT NOT NULL
);

CREATE TABLE entrada (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  autor_id INTEGER NOT NULL,
  creada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  titulo TEXT NOT NULL,
  cuerpo TEXT NOT NULL,
  FOREIGN KEY (autor_id) REFERENCES usuario (id)
);

